export const SAVE_ORG_DETAILS ='SAVE_ORG_DETAILS'



export const START_SAVE_PLASMA = 'START_SAVE_PLASMA';
export const ON_SAVE_PLASMA = 'ON_SAVE_PLASMA';
export const ERROR_SAVE_PLASMA = 'ERROR_SAVE_PLASMA';
export const ON_CLICK_DONAR_MODAL = 'ON_CLICK_DONAR_MODAL';
export const ON_CLOSE_DONAR_MODAL = 'ON_CLOSE_DONAR_MODAL';

export const START_FETCH_PLASMA = 'START_FETCH_PLASMA';
export const ON_FETCH_PLASMA = 'ON_FETCH_PLASMA';
export const ERROR_FETCH_PLASMA = 'ERROR_FETCH_PLASMA';



export const START_SAVE_PLASMA_REQ = 'START_SAVE_PLASMA_REQ';
export const ON_SAVE_PLASMA_REQ = 'ON_SAVE_PLASMA_REQ';
export const ERROR_SAVE_PLASMA_REQ = 'ERROR_SAVE_PLASMA_REQ';
export const ON_CLICK_REQUESTER_MODAL = 'ON_CLICK_REQUESTER_MODAL';
export const ON_CLOSE_REQUESTER_MODAL = 'ON_CLOSE_REQUESTER_MODAL';

export const START_FETCH_PLASMA_REQ = 'START_FETCH_PLASMA_REQ';
export const ON_FETCH_PLASMA_REQ = 'ON_FETCH_PLASMA_REQ';
export const ERROR_FETCH_PLASMA_REQ = 'ERROR_FETCH_PLASMA_REQ';


export const START_FEEDBACK = 'START_FETCH_PLASMA_REQ';
export const ON_SUCCESS_FEEDBACK = 'ON_FETCH_PLASMA_REQ';
export const ERROR_FEEDBACK = 'ERROR_FETCH_PLASMA_REQ';
export const ON_CLOSE_SUCCESS_FEEDBACK = 'ON_CLOSE_SUCCESS_FEEDBACK';

export const START_DEACTIVATE = 'START_DEACTIVATE';
export const ON_SUCCESS_DEACTIVATE = 'ON_SUCCESS_DEACTIVATE';
export const ERROR_DEACTIVATE = 'ERROR_DEACTIVATE';
export const ON_CLOSE_SUCCESS_DEACTIVATE = 'ON_CLOSE_SUCCESS_DEACTIVATE';
export const ON_CLICK_DEACTIVATE_MODAL = 'ON_CLICK_DEACTIVATE_MODAL';
export const ON_CLOSE_DEACTIVATE_MODAL = 'ON_CLOSE_DEACTIVATE_MODAL';
export const PHONE_NUMBER_EXITS = 'PHONE_NUMBER_EXITS';

export const FEEDBACK = 'Feedback'


export const OPEN_FILTER = 'OPEN_FILTER';
export const CLOSE_FILTER = 'CLOSE_FILTER';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const START_AUTH = 'START_AUTH';
export const ERROR_AUTH = 'ERROR_AUTH';


export const START_LOGOUT = 'START_LOGOUT';
export const ERROR_LOGOUT = 'ERROR_LOGOUT';

export const OPEN_LOGIN_MODEL = 'OPEN_LOGIN_MODEL';
export const CLOSE_LOGIN_MODEL = 'OPEN_LOGIN_MODEL';

export const ON_CLOSE_INFO_BOX = 'ON_CLOSE_INFO_BOX';


export const ON_SAVE_COVID_BEDS = 'ON_SAVE_COVID_BEDS';
export const START_SAVE_COVID_BEDS = 'START_SAVE_COVID_BEDS';
export const ERROR_SAVE_COVID_BEDS = 'ERROR_SAVE_COVID_BEDS';

export const ON_FETCH_COVID_BEDS = 'ON_FETCH_COVID_BEDS';
export const START_FETCH_COVID_BEDS = 'START_FETCH_COVID_BEDS';
export const ERROR_FETCH_COVID_BEDS = 'ERROR_FETCH_COVID_BEDS';


export const ON_SAVE_COVID_BEDS_REQ = 'ON_SAVE_COVID_BEDS_REQ';
export const START_SAVE_COVID_BEDS_REQ = 'START_SAVE_COVID_BEDS_REQ';
export const ERROR_SAVE_COVID_BEDS_REQ = 'ERROR_SAVE_COVID_BEDS_REQ';

export const ON_FETCH_COVID_BEDS_REQ = 'ON_FETCH_COVID_BEDS_REQ';
export const START_FETCH_COVID_BEDS_REQ = 'START_FETCH_COVID_BEDS_REQ';
export const ERROR_FETCH_COVID_BEDS_REQ = 'ERROR_FETCH_COVID_BEDS_REQ';



export const ON_SAVE_FOOD_DONATE = 'ON_SAVE_FOOD_DONATE';
export const START_SAVE_FOOD_DONATE = 'START_SAVE_FOOD_DONATE';
export const ERROR_SAVE_FOOD_DONATE = 'ERROR_SAVE_FOOD_DONATE';

export const ON_FETCH_FOOD_DONATE = 'ON_FETCH_FOOD_DONATE';
export const START_FETCH_FOOD_DONATE = 'START_FETCH_FOOD_DONATE';
export const ERROR_FETCH_FOOD_DONATE = 'ERROR_FETCH_FOOD_DONATE';


export const ON_SAVE_FOOD_DONATE_REQ = 'ON_SAVE_FOOD_DONATE_REQ';
export const START_SAVE_FOOD_DONATE_REQ = 'START_SAVE_FOOD_DONATE_REQ';
export const ERROR_SAVE_FOOD_DONATE_REQ = 'ERROR_SAVE_FOOD_DONATE_REQ';

export const ON_FETCH_FOOD_DONATE_REQ = 'ON_FETCH_FOOD_DONATE_REQ';
export const START_FETCH_FOOD_DONATE_REQ = 'START_FETCH_FOOD_DONATE_REQ';
export const ERROR_FETCH_FOOD_DONATE_REQ = 'ERROR_FETCH_FOOD_DONATE_REQ';

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const OPEN_INFO_MODAL = 'OPEN_INFO_MODAL'
export const CLOSE_INFO_MODAL = 'CLOSE_INFO_MODAL'

export const ON_CLICK_DEALER_MODAL = 'ON_CLICK_DEALER_MODAL';
export const ON_CLICK_OXYGEN_REQUESTER_MODAL='ON_CLICK_OXYGEN_REQUESTER_MODAL';
export const START_SAVE_OXYGEN="START_SAVE_OXYGEN";
export const ON_SAVE_OXYGEN="ON_SAVE_OXYGEN";
export const START_FETCH_OXYGEN="START_FETCH_OXYGEN";
export const ERROR_FETCH_OXYGEN="ERROR_FETCH_OXYGEN";
export const ERROR_SAVE_OXYGEN="ERROR_SAVE_OXYGEN";
export const ON_FETCH_OXYGEN="ON_FETCH_OXYGEN";
export const START_SAVE_OXYGEN_REQ="START_SAVE_OXYGEN_REQ";
export const ON_SAVE_OXYGEN_REQ="ON_SAVE_OXYGEN_REQ";
export const ERROR_FETCH_OXYGEN_REQ="ERROR_FETCH_OXYGEN_REQ";
export const ON_FETCH_OXYGEN_REQ="ON_FETCH_OXYGEN_REQ";
export const START_FETCH_OXYGEN_REQ="START_FETCH_OXYGEN_REQ";
export const ERROR_SAVE_OXYGEN_REQ="ERROR_SAVE_OXYGEN_REQ";
export const ON_CLOSE_OXYGEN_REQUESTER_MODAL="ON_CLOSE_OXYGEN_REQUESTER_MODAL";
export const ON_CLOSE_DEALER_MODAL="ON_CLOSE_DEALER_MODAL";
export const OPEN_OXYGEN_FILTER="OPEN_OXYGEN_FILTER";
export const CLOSE_OXYGEN_FILTER="CLOSE_OXYGEN_FILTER";
export const ON_CLICK_OXYGEN_DEACTIVATE_MODAL="ON_CLICK_OXYGEN_DEACTIVATE_MODAL";
export const ON_CLOSE_OXYGEN_DEACTIVATE_MODAL="ON_CLOSE_OXYGEN_DEACTIVATE_MODAL";
export const CLOSE_OXYGEN_INFO_MODAL="CLOSE_OXYGEN_INFO_MODAL";

